### ISSUE TITLE
Getting error Invalid IV length

### ISSUE THREAD

**Issue by ratnesh258** [NewRedo/sagepay-form#3]
Hello I am trying to integrate sagepay-form to node js and i am getting this error
Error: Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20)
    at new Cipheriv (internal/crypto/cipher.js:217:22)
    at Object.createCipheriv (crypto.js:109:10)
    at SagepayForm.createHiddenFields (/home/yashco/ratnesh_data/node_JS_application/sagepay-form/client.js:39:29)
    at /home/yashco/ratnesh_data/node_JS_application/sagepay-form/example/index.js:39:38
    at Layer.handle [as handle_request] (/home/yashco/ratnesh_data/node_JS_application/sagepay-form/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/yashco/ratnesh_data/node_JS_application/sagepay-form/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/yashco/ratnesh_data/node_JS_application/sagepay-form/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/yashco/ratnesh_data/node_JS_application/sagepay-form/node_modules/express/lib/router/layer.js:95:5)

**Comment by pluby** [comment]
It looks like the example is being run without providing a valid `VENDOR_PASSWORD`.

**Comment by xor83** [comment]
having same problem
